STT_Task:
  description: >
    You put ON the microphone or takes input from the twilio of the phone call and convert it into text.
  expected_output: >
    The text transcription of the audio.
  agent: STT_Agent

LLM_task:
  description: >
    You understands the user's question and responds to it using a powerful local LLM (Mistral) to respond to user queries with natural responses.
  expected_output: >
    The response from the LLM.
  agent: LLM_Agent

TTS_task:
  description: >
    You understands the response from the local LLM (Mistral) and convert 
    the response to Speech with beautiful voice response.
  expected_output: >
    Audio responding to the query.
  agent: TTS_Agent

Data_Extractor_Task:
  description: >
    You understands the user's question and extracts the relevant data from the database like name, email, interest 
    and other things that might help to understand more about the customer.
  expected_output: >
    The relevant data from the database.
  agent: Data_Extractor_Agent
